### ISSUE TITLE
BUG: Windows phones also get iOS Appstore page

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#104]

**Comment by robbert** [comment]
Windows Phones pretend to be iPhones apparently:

http://wmpoweruser.com/wp8-1-update-1s-ie-user-agent-pretends-to-be-android-4-0-and-ios-7-good-enough-to-fool-gmail/

**Comment by MichelvanderAa** [comment]
pls fix keyboard bug first before spending time on this!

**Comment by robbert** [comment]
Fixed.

**Comment by MichelvanderAa** [comment]
Sigi zegt: "Er staat nog steeds your brouwser is not supported by this website"

De site deed het voorheen wel gewoon goed op haar Windows phone

**Comment by robbert** [comment]
This was deliberate, because I wasn't sure if the site actually worked on Windows Phone, but apparently it did work. Removed `IEMobile` from the blacklist.

**Comment by MichelvanderAa** [comment]
still only partially fixed;  it seems you have to put the phone in 'desktop mode' for the site to load. Otherwise it shows the iOS app page.  
Maybe has to do with screen resolution?   Can't you set it so that Windows phones also get straight access to the site and the .app page is ignored?

**Comment by robbert** [comment]
Working on this again. Testing with someone else Windows Phone right now.

**Comment by robbert** [comment]
![photo on 01-06-15 at 16 03 2](https://cloud.githubusercontent.com/assets/30694/7914540/e51cba32-0877-11e5-854f-6808f287e336.jpg)

**Comment by MichelvanderAa** [comment]
Sigi bevestigd, het werkt nu :-)
